[package]
name = "ruxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.*"
lazy_static = "1.1.*"
pollster = "0.3.*"
wgpu = "0.15.*"
wgpu-hal = "0.15.*"
winit = "0.28.*"
