name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with v, e.g., v1.0.0

permissions:
  contents: write

jobs:
  release:
    name: Build ruxel for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: ruxel.exe
            asset_name: ruxel-windows.exe
          - os: macos-latest
            artifact_name: ruxel
            asset_name: ruxel-macos
          - os: ubuntu-latest
            artifact_name: ruxel
            asset_name: ruxel-linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-wgsl
        run: cargo install cargo-wgsl --locked

      - name: Build release binary
        run: make build_release_opt

      - name: Create test outputs directory
        run: mkdir -p test_outputs
        shell: bash

      - name: Run tests
        run: make test_release_opt_all

      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          compress-archive -path target/release-opt/ruxel.exe -destinationpath ruxel-windows.zip

      - name: Package macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd target/release-opt
          zip -r ../../ruxel-macos.zip ruxel

      - name: Package linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd target/release-opt
          zip -r ../../ruxel-linux.zip ruxel

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ruxel-windows.zip
            ruxel-macos.zip
            ruxel-linux.zip
          name: Release ${{ github.ref_name }}
          draft: true
